---
title: "Research Output"
---

Below is a list with links to my talks, posters, and papers, with each group being sorted from newest to oldest. 

## Selected Publications {.tabset .tabset-fade}

### Talks

1. Panizza, Daniele & Thalmann, Maik (2019): [Adults are not always faster than children. An eye-tracking study on the online comprehension of indirect scalar implicatures.](media/talks/XPrag-It_Panizza:Thalmann.pdf) XPRAGIT 3.
1. Antomo, Mailin; Chen, Yuqiu; Müller, Susanne; Paul, Katharina; Paluch, Markus & Thalmann, Maik (2019): [Deceptive language: a new methodology in language acquisition and implicature theory.](media/talks/DGfS_Antomo:Chen:Müller:Paluch:Paul:Thalmann.pdf) DGfS 41.
1. Thalmann, Maik (2019): [Presuppositions At-Issue: Soft and Hard Triggers in Language Acquisition.](media/talks/Vienna_Thalmann.pdf) Vienna.

### Posters

1. Panizza, Daniele & Thalmann, Maik (2019): [Adults are not always faster than children. An eye-tracking study on the online comprehension of Indirect Scalar Implicatures.](media/posters/AMLaP_Thalmann:Panizza.pdf) GALA 14.
1. Roszowski, Magdalena; Schmitt, Viola; Thalmann, Maik & Panizza, Daniele (2019): [On the role of distribuitivity in the online comprehension of VP-conjunction.](media/posters/XPrag-It_Roszowski:Schmitt:Thalmann:Panizza.pdf) XPRAGIT 3.
1. Thalmann, Maik & Panizza, Daniele (2019): [Adults are not always faster than children. An eye-tracking study on the online comprehension of Indirect Scalar Implicatures.](media/posters/AMLaP_Thalmann:Panizza.pdf) AMLaP 25.
1. Thalmann, Maik & Panizza, Daniele (2018): [Present to the eye, away from the mind. Dissociating online comprehension and offline judgments of indirect scalar inferences.](media/posters/BUCLD_Thalmann:Panizza_Poster.pdf) BUCLD 43.
1. Thalmann, Maik; Paul, Katharina & Panizza, Daniele (2018): [When Children Process Ambiguity Faster Than Adults: Evidence from Eye Movements.](media/posters/Ambigo_Thalmann:Paul:Panizza.pdf) Ambigo.
1. Roszowski, Magdalena; Schmitt, Viola; Thalmann, Maik & Panizza, Daniele (2018): [Experimental Evidence for non-Intersective VP-Conjunction In Children and Adults.](media/posters/Ambigo_Roszowski:Schmitt:Thalmann:Panizza.pdf) Ambigo.

### Papers (Preprint)

<!-- 1. Thalmann, Chen, Müller, Paluch & Antomo (*submitted*): [Against PCI-GCI uniformity. Evidence from deceptive language in German and Chinese.](media/papers/LB_Thalmann:Chen:Müller:Paluch:Antomo.pdf) Linguistische Berichte. -->
1. Thalmann, Maik & Panizza, Daniele (2019): [Present to the Eye, Away from the Mind. Dissociating Online Comprehension and Offline Judgments of Indirect Scalar Inferences.](http://www.lingref.com/bucld/43/BUCLD43-52.pdf) Proceedings of BUCLD 43.
1. Antomo, Mailin; Chen, Yuqiu; Müller, Susanne; Paul, Katharina; Paluch, Markus & Thalmann, Maik (2018): [When children aren't more logical than adults. An empirical investigation of lying by falsely implicating.](https://doi.org/10.1016/j.pragma.2018.09.010) Journal of Pragmatics.
